name:                unboxing-vector
version:             0.1.1.0
github:              "minoki/unboxing-vector"
license:             BSD3
author:              "ARATA Mizuki <minorinoki@gmail.com>"
maintainer:          "ARATA Mizuki <minorinoki@gmail.com>"
copyright:           "2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A newtype-friendly variant of unboxed vectors
category:            Data, Data Structures

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/unboxing-vector#readme>

dependencies:
- base >= 4.9 && < 5  # Data.Semigroup is available since 4.9.0.0
- vector
- deepseq
- primitive
- mono-traversable

ghc-options:
- -Wall

library:
  source-dirs: src
  other-modules:
  - Data.Vector.Unboxing.Internal
  tested-with: GHC == 8.6.5, GHC == 8.4.4, GHC == 8.2.2

benchmarks:
  unboxing-vector-benchmark:
    main:                Bench.hs
    source-dirs:         benchmark
    ghc-options:
    - -rtsopts
    dependencies:
    - unboxing-vector

tests:
  unboxing-vector-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wno-missing-signatures
    dependencies:
    - unboxing-vector
    - HUnit
    - should-not-typecheck

  # GND with associated type families is available since GHC 8.2
  unboxing-vector-test-gnd:
    main:                Spec.hs
    source-dirs:         test-gnd
    ghc-options:
    - -Wno-missing-signatures
    dependencies:
    - unboxing-vector
    - HUnit
    when:
    - condition: impl(ghc >= 8.2.1)
      then:
        buildable: True
      else:
        buildable: False

  # DerivingVia is available since GHC 8.6
  unboxing-vector-test-deriving-via:
    main:                Spec.hs
    source-dirs:         test-deriving-via
    ghc-options:
    - -Wno-missing-signatures
    dependencies:
    - unboxing-vector
    - HUnit
    - should-not-typecheck
    when:
    - condition: impl(ghc >= 8.6.1)
      then:
        buildable: True
      else:
        buildable: False
