on: [push, pull_request]
name: build
jobs:
  unboxing-vector:
    name: unboxing-vector
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.0.2', '8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.7', '9.0.2', '9.2', '9.4']
        os: [ubuntu-latest]
        flags: ['', '--flags=-mono-traversable']
        vector-version: ['0.12.0.*', '0.12.*', '0.13.*']
        exclude:
          - ghc: '8.10.7'
            vector-version: '0.12.0.*'
          - ghc: '9.0.2'
            vector-version: '0.12.0.*'
          - ghc: '9.2'
            vector-version: '0.12.0.*'
          - ghc: '9.4'
            vector-version: '0.12.0.*'
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - name: Build
        run: cabal build unboxing-vector --ghc-options=-fno-ignore-asserts --enable-tests --enable-benchmarks --constraint="vector==${{ matrix.vector-version }}" ${{ matrix.flags }}

      - name: Test
        run: cabal test --ghc-options=-fno-ignore-asserts --constraint="vector==${{ matrix.vector-version }}" ${{ matrix.flags }}
